import { Inter } from "next/font/google";
import "./globals.css";
import express from 'express';

const inter = Inter({ subsets: ["latin"] });

const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

export const metadata = {
  title: "Bedrock Chatbot Demo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
